name: Counter-Strike | Compiler

on:
  push:
    branches: ["main" ]


jobs:

  build:
        runs-on: ubuntu-latest
        steps:
            -   name: Build and push docker image
                uses: docker/build-push-action@v1
                with:
                    username: androcyber
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    dockerfile: Dockerfile
                    repository: androcyber/yolks
                    tag_with_ref: true
