name: Counter-Strike | Compiler

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    name: "compiler"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHRC_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./Counter-Strike
          file: ./Counter-Strike/compiler/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/androcyber/yolks:compiler
