name: Counter-Strike | Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: "Docker Hub'dan çıkış yapılıyor..."
      run: docker logout
      
    - name: "Docker Hub'a giriş yapılıyor..."
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ USERNAME }}
        password: ${{ secrets.GHRC_PASSWORD }}
        
    - name: "Docker Image yayınlanıyor..."
      uses: docker/build-push-action@v4
      with:
        run: docker logout
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ USERNAME }} --password-stdin
        push: true
        file: ./Counter-Strike/compiler/Dockerfile
        tags: ${{ USERNAME }}/yolks:compiler
