name: Counter-Strike | Compiler

on:
  push:
    branches:
    - "main/Counter-Strike/compiler"
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker logout | 
        echo "${{ secrets.DOCKERPW }}" | docker login -u "androcyber" --password-stdin
        docker image build -t androcyber/yolks:compiler .
        docker push androcyber/yolks:compiler
