name: Counter-Strike | Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: "Docker Hub'dan çıkış yapılıyor..."
      run: docker logout
      
    - name: "Docker Hub'a giriş yapılıyor..."
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: androcyber
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: "Docker Image yayınlanıyor..."
      uses: docker/build-push-action@v4
      with:
        push: true
        file: ./Counter-Strike/compiler/Dockerfile
        tags: androcyber/yolks:compiler
