name: Counter-Strike | Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: "Docker Hub'dan çıkış yapılıyor..."
      run: docker logout
      
    - name: "Docker Hub'a giriş yapılıyor..."
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: androcyber
        password: "${{ secrets.GHRC_PASSWORD }}"
    - name: Build the Docker image
      run: docker build . --file ./Counter-Strike/compiler/Dockerfile --tag my-image-name:$(date +%s)
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker logout | 
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "androcyber" --password-stdin
        docker image build -t androcyber/yolks:compiler .
        docker push androcyber/yolks:compiler
