name: Discord Bot | discord.py

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWD }}
      - uses: docker/build-push-action@v4
        with:
          context: ./Discord Bot/discord.py
          file: ./Discord Bot/discord.py/Dockerfile
          push: true
          tags: |
            ghcr.io/androcyber/yolks:discordpy
